package deamwhitten.appointmentscheduler.Controller;

import deamwhitten.appointmentscheduler.Utils.Collections.Counties_Collections;
import deamwhitten.appointmentscheduler.Utils.Collections.Customers_Collections;
import deamwhitten.appointmentscheduler.Utils.Collections.Divisions_Collections;
import deamwhitten.appointmentscheduler.Utils.Window_Handler;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

public class Add_Customer_Controller implements Initializable {
    @FXML
    private TextField customerID_input;
    @FXML
    private TextField  name_input;
    @FXML
    private TextField phoneNumber_input;
    @FXML
    private TextField address_input;
    @FXML
    private TextField postalCode_input;
    @FXML
    private ComboBox<String> country_selection;
    @FXML
    private ComboBox<String> division_selection;
    @FXML
    private Label error_label;

    private static int autoGeneratedCustomerID;

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        autoGeneratedCustomerID = Customers_Collections.getAllCustomers().size() + 1;
        country_selection.getItems().addAll(Counties_Collections.getAllCountiesNames());

    }

    @FXML
    public void onCountrySelected(ActionEvent event) {
        division_selection.getItems().clear();
        String selectedCounty = country_selection.getSelectionModel().getSelectedItem();
        if(selectedCounty != null){
            division_selection.getItems().addAll(Divisions_Collections.getSelectedDivisionNamesByCountryID(selectedCounty));
        }

    }

    @FXML
    public void onAddCustomerClick(ActionEvent event) throws IOException {
        Boolean isValidInput = validateInput();
        if(isValidInput){
            Window_Handler.loadWindow("MainWindow_View","Appointment Scheduler", event);
        } else {
            getErrorMsg();
        }
    }

    @FXML
    public void  onCancelAddCustomerClick(ActionEvent event) throws IOException {
        Window_Handler.loadWindow("MainWindow_View","Appointment Scheduler", event);
    }

    private void getErrorMsg() {
    }

    private Boolean validateInput() {

        return true;
    }
}